-- AlterTable
ALTER TABLE `InternshipGroupStudent` ADD COLUMN `internshipNote` TEXT NULL,
    ADD COLUMN `internshipRegulation` VARCHAR(255) NOT NULL DEFAULT '[]',
    ADD COLUMN `internshipResult` ENUM('WAITING', 'UNFINISHED', 'DONE_AVERAGE', 'DONE_ABOVE_AVERAGE', 'DONE_PROFICIENT', 'DONE_EXCELLENT') NOT NULL DEFAULT 'WAITING';
